### PR TITLE
Haproxy Extension Check

### PR DESCRIPTION
**Pull request by Igorshp**
Converted community plugin check_haproxy.rb to extension format
https://github.com/sensu/sensu-community-plugins/blob/master/plugins/haproxy/check-haproxy.rb
Functionality is unchanged

Added usage example in the comments.

REQUIRES SENSU 0.17.1 OR HIGHER

### CODE REVIEW

**Comment by Igorshp** [comment]
![brace yourself]
(http://i.imgur.com/adqoj8Y.jpg)

**Comment by Igorshp** [comment]
Added tests, that did catch a couple of small things and one big problem.

https://github.com/Igorshp/sensu-community-plugins/blob/haproxy_extension/extensions/checks/haproxy.rb#L119

left over from normal checks. unknown supposed to return status 3 and a message.
I'm looking for suggestions on how to best bubble the error up #run level so it can be yielded correctly.

**Comment by mattyjones** [comment]
@Igorshp 
can you take a look at the travis issue

Also when can you make a pr against the new sensu-plugins-haproxy repo as well

Thanks!

**Comment by Igorshp** [comment]
@mattyjones i know what the travis issue is. The extension is not 100% complete yet. I designed the test  specifically to highlight a problem in the code.

I'm looking for help/suggestions/ideas on best way to bubble up error from a sub-function to a #run block.

**Comment by Igorshp** [comment]
@mattyjones The travis error was deliberate, i'm still looking for a clean way to bubble up errors to the level of #run function.

As soon as this PR is fully done and merged, i'll submit a copy to the sensu-plugins-haproxy repo as well.

**Comment by mattyjones** [comment]
Could you please also pull against [sensu-plugins-haproxy](https://github.com/sensu-plugins/sensu-plugins-haproxy)

Thanks!

**Pull request merged**
