### PR TITLE
JSON.parse is not working.

### PR DESCRIPTION
**Pull request by guerremdq**
Should use JSON generate here.

### CODE REVIEW

**Comment by portertech** [comment]
Should probably just use `dump()`.

**Comment by guerremdq** [comment]
Switched to dump.

**Comment by analytically** [comment]
Hi, can you open a PR against https://github.com/sensu-plugins/sensu-plugins-logstash - this repository is deprecated!

**Comment by guerremdq** [comment]
On the other repository is using JSON.generate that one works too.

**Pull request closed without merging**
