### PR TITLE
btrfs check + make check-tripwire go in its own directory like everyone else.

### PR DESCRIPTION
**Pull request by sge-babrams**
make tripwire be in its own directory just like everyone else

Added btrfs check. I do not write the initial check you can see it here: https://gist.github.com/tim-adlibre/7af97a712568c6240ee1

This was verified in a docker container running the sensu client. The host was coreos which has / as btrfs.

### CODE REVIEW

**Comment by sge-babrams** [comment]
also here is output of a warning and crit (using options):

root@9d8cef64e568:/etc/sensu# ./plugins/aio/check-btrfs.rb -w 10 -c 90
CheckBtrfs WARNING: /dev/xvda9 24.69%

root@9d8cef64e568:/etc/sensu# ./plugins/aio/check-btrfs.rb -w 10 -c 24
CheckBtrfs CRITICAL: /dev/xvda9 24.69%

**Comment by mattyjones** [comment]
I won't move the location of tripwire as that is breaking and that change is already done in the new.  Could you please resubmit your PR with only the script.

In the future things like this should also be separate PR's as they involve separate code.  This makes it a lot easier to troubleshoot and roll forward if need be

Thanks!

**Comment by sge-babrams** [comment]
@mattyjones np...separated out and passing rubocop: https://github.com/sensu/sensu-community-plugins/pull/1064 . Also is "that change is already done in the new repo." can you point me at the new repo?

**Comment by mattyjones** [comment]
[sensu-plugins-tripwire](https://github.com/sensu-plugins/sensu-plugins-tripwire)

**Pull request closed without merging**
