### PR TITLE
Remove multiple Ruby 1.8.7 checks

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by soichih** [comment]
Does this mean ruby 1.8.7 (the version that comes with RHEL6) is no longer supported?

**Comment by sensu-plugin** [comment]
That is correct.  You can simply use the embedded Ruby that comes with Sensu and not need to worry about trying to support an EOL Ruby.

**Comment by soichih** [comment]
Great! I didn't know about embedded Ruby. I just looked it up, and set following option
> EMBEDDED_RUBY=true in /etc/default/sensu
And now my check-cron test is running correctly!

However, when I run the command manually on command line, it still uses the OS default ruby (and fails)

```
$ /etc/sensu/plugins/check-procs.rb -p cron
/etc/sensu/plugins/check-procs.rb:34: syntax error, unexpected ':', expecting kEND
         short: '-w N',
               ^
```

How can I force it to run with the "embedded ruby" via the command line?

**Comment by sensu-plugin** [comment]
In my check definitions I just use the full path

`/opt/sensu/embedded/bin/ruby /path/to/check.rb`

**Pull request merged**
