### PR TITLE
Add metrics-chrony

### PR DESCRIPTION
**Pull request by maoe**
This PR introduces a new metrics plugin for [Chrony](http://chrony.tuxfamily.org/). It replicates the behavior of [metrics-ntpstats](https://github.com/sensu-plugins/sensu-plugins-ntp/blob/master/bin/metrics-ntpstats.rb).

### CODE REVIEW

**Comment by maoe** [comment]
All the errors on Travis are from `rabbitmq/check-rabbitmq-messages.rb`.

**Comment by maoe** [comment]
Do you still accept fixes? I just pushed small changes to improve nil handling and negative values handling.

**Comment by maoe** [comment]
If it's better to squash commits, please let me know.

**Comment by analytically** [comment]
Hi, thanks for your PR. We should create a new crony plugin for this. @mattyjones can you create the repo?

**Pull request closed without merging**
