### PR TITLE
Add check-whois.rb

### PR DESCRIPTION
**Pull request by mijit**
A plugin to check domain expiration date with the 'whois' gem

### CODE REVIEW

**Comment by mattyjones** [comment]
@mijit Could you please take a look at the Travis output.  Thanks!

**Comment by mijit** [comment]
Done! Thanks for notifying me.

**Comment by mattyjones** [comment]
@rmc3 Where do you think this should go in the new org, network-checks or somewhere else?

**Comment by rmc3** [comment]
@mattyjones network-checks makes the most sense to me.

**Comment by mattyjones** [comment]
@mijit Could you please make a pr against [sensu-plugins-network-checks](https://github.com/sensu-plugins/sensu-plugins-network-checks) as well.

Thanks!

**Pull request merged**
