### PR TITLE
Support a prefix to prepend to the event_summary for PagerDuty.

### PR DESCRIPTION
**Pull request by analytically**

### CODE REVIEW

**Comment by mattyjones** [comment]
@analytically  Can you please take a look at the Travis output.
Thanks!

**Comment by analytically** [comment]
"Warning: unrecognized cop FileName found in /home/travis/build/sensu/sensu-community-plugins/.rubocop.yml" - my PR doesn't touch this, so I think Travis is/was broken.

**Comment by analytically** [comment]
Gonna make a new PR.

**Comment by mattyjones** [comment]
@analytically  I have seen that on occasion as well, I am leaning towards it is a Rubocop issue.  I haven't had the time and frankly, the desire, to dig into it further.

**Comment by analytically** [comment]
https://github.com/sensu/sensu-community-plugins/pull/1024

**Pull request closed without merging**
