### PR TITLE
Windows WMI metrics accumulate network data over interval

### PR DESCRIPTION
**Pull request by cloakedcode**
The current `wmi_metrics.rb` extension check polls every 10sec by default, resulting in 6 1sec datapoints. This means you have values for those 6 seconds spread across the minute, instead of an accumulative value for the whole minute.

These changes total the network traffic datapoints over 60 seconds, polling every 1sec with a periodic timer. All other metrics are polled once every 60 seconds.

### CODE REVIEW

**Comment by mattyjones** [comment]
@rmc windows is your baby, thoughts on this

**Comment by rmc3** [comment]
Looks pretty good to me, thanks for working on this @cloakedcode 

Three thoughts:

1. It might be useful to have a way to roll up accumulated metrics (such as averaging or summing) over the run interval, keeping to the convention of having one run of a metric check produce one data point for each metric and reducing the amount of complexity required for metric backends receiving this data.

2. Is there any reason only network metrics are accumulated and not the other metric types?

3. It may be useful to allow arbitrary provider paths to be passed in via the extension's configuration. There are many other metric endpoints provided by WMI that users of this extension may wish to collect. This may be outside the scope of this extension (or be something that users could add as a customization if they wished.

**Comment by cloakedcode** [comment]
@rmc3 Some responses:

 1. If you look carefully you'll notice the code already allows for summing of datapoints. That's how the network metrics are calculated (i.e. by calling `add_metrics` multiple time).

 2. The other metric types are not cumulative because their data doesn't fit that model well. CPU load of 50% summed over a minute would result in a response of 50% * 60, which, is far above the actual load for that minute, 50%. Same thing for memory usage. Maybe it should be cumulative for disk usage.

 3. That's a good idea. I was going to comb through what WMI exposes and add all the sane providers by default. It might be more useful to have this integrated into the config.

**Comment by rmc3** [comment]
1. Gotcha! That's what I get for reading this code before being caffeinated. 

2. That makes sense. Thanks for the explanation.

**Comment by rmc3** [comment]
@mattyjones Point #3 aside which is really just a convenience feature, I think this is merge-worthy.

**Comment by mattyjones** [comment]
@rmc3 Should we make a PR against [sensu-plugins-windows](https://github.com/sensu-plugins/sensu-plugins-windows)

**Comment by rmc3** [comment]
@mattyjones Yes, that seems like the proper place for this to be.

**Comment by mattyjones** [comment]
@cloakedcode  could you please make a PR against the above repo if you get a moment as that will be the final resting place for the functionality

**Pull request merged**
