### PR TITLE
Added freesmsalert handler

### PR DESCRIPTION
**Pull request by meatheadmike**

### CODE REVIEW

**Comment by mattyjones** [comment]
@meatheadmike Could you also please make a PR against [sensu-plugins-sms](https://github.com/sensu-plugins/sensu-plugins-sms) as well.

Thanks!

**Comment by meatheadmike** [comment]
Sure thing. Should I just PR the same 3 files, or is there something
special I need to do with the separate release?

**Comment by mattyjones** [comment]
It is a new repo, so add all your stuff in.  The only thing to watch for is the linting much tighter in the new org.

Thanks

**Comment by meatheadmike** [comment]
So am I forking off of sensu-plugins/sensu-plugin and then PRing to
sensu-plugins-sms? I not clear on the new framework. Are there docs you can
point me to?

**Comment by mattyjones** [comment]
@meatheadmike 

They are in the works, I created a sensu-plugins-sms repo, just fork and pr it like it was the community-plugins repo.  Each 'directory' and then some now has its own repo and will be built into a gem and released to ruby gems.

**Pull request merged**
