### PR TITLE
Add mtu check

### PR DESCRIPTION
**Pull request by robin81**
### When are these checks useful
1. Systems' MTUs are often tuned. MTU mismatches result in issues. 
1. Certain Amazon EC2 Linux instances are booted up with MTU 9,000 (instead of typical 1,500). It can be undesirable in some settings.

### Notes
`rubocop:disable Metrics/AbcSize` is done on `def run`.

### CODE REVIEW

**Comment by mattyjones** [comment]
@robin81 Can you take a look at the Travis output please.

Could you also do a PR against [sensu-plugins-network-checks](https://github.com/sensu-plugins/sensu-plugins-network-checks)

Thanks!

**Comment by robin81** [comment]
Thanks @mattyjones ; I will make a PR against sensu-plugins-network-checks and update the`rspec`-related code.  My apologies: `rspec` was passing on my local environment (but not on travis CI). I'll be sure to test the `rspec` in a cleaner environment via the Vagrant provided in the repo.

**Comment by robin81** [comment]
Per @mattyjones, also opened a PR: 
https://github.com/sensu-plugins/sensu-plugins-network-checks/pull/9

**Comment by robin81** [comment]
@mattyjones All the requested changes have been completed. OK to merge this one ?

**Pull request merged**
