### PR TITLE
Multiple hosts supported with additional matching options

### PR DESCRIPTION
**Pull request by raags**
* Added support for multiple host pattern matching, with success based on the number of matches. This can be used for example to check that a Zookeeper ensemble has a single leader.
* Added ability to read banner till a custom character is reached. For example read till EOF and EOL. 
* Options to override ok and critical message.
* The default behaviour of the check before this change remains the same.

### CODE REVIEW

**Comment by mattyjones** [comment]
Awesome!  Could you also make a PR against here as weel. [sensu-plugins-zookeeper](https://github.com/sensu-plugins/sensu-plugins-zookeeper).

Thanks!

**Comment by raags** [comment]
This is a generic check, I think it should come under sensu-plugins-network

**Comment by mattyjones** [comment]
@raags 

You are correct, :facepalm

There has already been a lot of work done on that repo so it may be a manual merge on your end but give it a go.

**Comment by raags** [comment]
Done, sent a PR there : https://github.com/sensu/sensu-community-plugins/pull/1078

**Pull request closed without merging**
