### PR TITLE
Add IAM Role support to existing AWS plugins and remove fog gem dependencies

### LINKED ISSUE #707: All AWS checks, etc should support IAM roles by default
IAM roles are the AWS recommended way of assigning access tokens.

### PR DESCRIPTION
**Pull request by bkett**
Resolves #707

### CODE REVIEW

**Comment by mattyjones** [comment]
@bkett I will merge this Monday.  I just sent out a change request to the users group for the sake of being polite as this is a fairly large change and these checks have a large user base I'm sure.

**Comment by bkett** [comment]
@mattyjones Ok that's fine. Everything should theoretically be backwards compatible in terms of how you run each check :)

**Comment by mattyjones** [comment]
I appreciate that.  I will confirm that this weekend but for the sake of
being open I want to make sure people have a chance to pin as not everyone
has the same requirements, etc for a monitoring system.

**Comment by bkett** [comment]
More than reasonable! I wouldn't want to be woken up or called in at 2am tomorrow morning either.

**Pull request merged**
