### PR TITLE
support html level check over http

### PR DESCRIPTION
**Pull request by abazinet**

### CODE REVIEW

**Comment by mattyjones** [comment]
@abazinet  Can you take a look at the Travis output please.  Thanks

**Comment by abazinet** [comment]
Hey @mattyjones I'm struggling a little bit with adding my nokogiri dependency, is there something that I am missing? thanks!

**Comment by mattyjones** [comment]
Start with what are you trying to do (big picture) so I can get some sense.  Then why are you using nokogiri v. X?  Just curious, not judging.  At that point we can start picking apart the code and I will try and give you a hand with it.

**Comment by abazinet** [comment]
I am adding a generic html check, i.e. actually check at the application level not just http level that the response makes sense. For example let's say the html coming back from the server was to be dynamically generated, this check could validate the actual html content. The way it is implemented right now is to use the nogokiri library to "parse" the html and run an xpath against that. The results from the xpath can then optionally be validated against a provided regex. Is this at the level you are looking for? thanks

**Comment by abazinet** [comment]
Oh by the way @mattyjones I don't mind to change nogokiri for another library if you have a better idea, with the current test coverage that should not be a big deal at all. I don't usually write ruby but from a noob it just seemed like the 'best' choice for this purpose.

**Comment by abazinet** [comment]
Hey @mattyjones is there anything that I could do to help get over this hump? thanks!

**Pull request closed without merging**
