### PR TITLE
Updated check-ram.rb to work with the new version of free 

### PR DESCRIPTION
**Pull request by srodman7689**
Updated check-ram.rb to work with the new version of free from procps-ng version 3.3.10

### CODE REVIEW

**Comment by srodman7689** [comment]
I just wanted to update this pull request to let you guys know that this problem came up after updating procps-ng last night on a CentOS Linux release 7.1.1503 (Core) box. Please let me know if you have any questions or if I need to change how I created the pull request.

**Comment by srodman7689** [comment]
I rewrote the check-ram.rb application to work with both the new and old versions of free. I had to push a third time to make sure that it takes into account the swap from the new command needed.

**Comment by srodman7689** [comment]
Have to change this again. one second.

**Comment by srodman7689** [comment]
This has been tested on both the 3.3.9 version of free and the 3.3.10 version and it works correctly. we are current deploying this check into production and haven't had any problems so far.

**Comment by srodman7689** [comment]
My math is off. closing until I fix it. one second.

**Comment by srodman7689** [comment]
Finally figured out the math. it works on both the old and new versions of free correctly. Please let me know if you guys have any questions.

**Comment by srodman7689** [comment]
Removed the unneeded -t option. Now that it is calculated a different way it is no longer needed.

**Comment by salizzar** [comment]
Hi @srodman7689,

Based on https://gitorious.org/procps/procps/commit/f47001c9e91a1e9b12db4497051a212cf49a87b1 from #1115, why not use column "available" instead of doing some math with buffers / cache?

**Comment by srodman7689** [comment]
I wanted to make the change compatible with both the old versions of free and the new ones. I could use the available column if that is what should happen but I just wanted a standard way to check between the two free outputs.

**Comment by srodman7689** [comment]
You were right about the available column. It ended up making the code more readable.

**Comment by srodman7689** [comment]
Is there anyway we could have these changes merged? Is there anything else I need to do to make that possible?

**Comment by mattyjones** [comment]
@srodman7689   Could you also pull against sensu-plugins-memory-checks

Thanks

**Pull request merged**
