### PR TITLE
Added support for nested keys in http-json-check

### PR DESCRIPTION
**Pull request by shaiguitar**
- Added a spec for http-json-check.
- This requires webmock for dev dependency (gemspec file).
- Run the test with:

  `$ bundle install; bundle exec rspec spec/plugins/http/check_json_spec.rb`

- Ran the script manually with ruby/like the example, worked fine.
- Added example documentation with single key, as was before.
- Added example documentation with nested key form.

### CODE REVIEW

**Comment by shaiguitar** [comment]
Not sure why travis build is failing:

`bundle exec rake default` 

Seems to work locally:

`177 examples, 0 failures`

Let me know if there's anything else that needs to be added/modified here.

**Comment by mattyjones** [comment]
@shaiguitar   Rubocop is puking all over the floor ;)  try `rubocop -a`

**Comment by shaiguitar** [comment]
Fixed rubocop offenses. The specific test added still passes as well with modifications.

` bundle install; bundle exec rspec spec/plugins/http/check_json_spec.rb`

**Comment by mattyjones** [comment]
@shaiguitar  Can you also pull these against sensu-plugins-http.

Thanks

**Comment by shaiguitar** [comment]
I'd be happy to, but not sure what that means

**Comment by mattyjones** [comment]
@shaiguitar [sensu-plugins-http](https://github.com/sensu-plugins/sensu-plugins-http)

**Comment by shaiguitar** [comment]
I'm a little confused why there's duplication of the same script in two different places. In any case that patch does not apply, looks like that functionality is already implemented in that one.

https://github.com/sensu-plugins/sensu-plugins-http/blob/master/bin/check-http-json.rb#L128

Thanks for merging here. Closing this out.

**Pull request merged**
