### PR TITLE
update check-mtime to detect if a file has zero size

### PR DESCRIPTION
**Pull request by zarry**
Simple change to add the ability to detect a file of zero size and pass/fail the check with that information in addition to the modified date and file being present.

Realistically having a file modified within a certain time frame is great, but if it is being modified and set as 0 file size it kind of defeats the purposes of ensuring it is being updated.  This will safe guard against that scenario.  In a case where that is acceptable you can override that behavior using the -z or --ok-zero-size options.

### CODE REVIEW

**Comment by mattyjones** [comment]
@zarry Have you made any progress rebasing this?  If you would like some help I may be able to devote some cycles to it, otherwise I would like to close this PR by the end of the week.  Feel free to open it again in the future. ;)

**Comment by zarry** [comment]
@mattyjones Apologies, looks like I had lost track of this.  Let me get this updated and merged this evening.

thanks!

**Comment by mattyjones** [comment]
@zarry No worries, most of us do this in what little spare time, if any, that we have.

**Comment by zarry** [comment]
Merged last night and again this morning.  Ran some tests on the behavior this morning and it all still functions as expected.  Let me know if you have any questions/concerns.

**Pull request merged**
